const labels = {
  id:'ID',
  projects: "案件一覧",
  project_name: "案件名",
  client_name: "クライアント",
  invoice_date: "請求日",
  estimate_date: "見積日",
  is_completed: "入金",
  is_completed2: "入金確認",
  is_canceled:"キャンセル",
  total_amount:"合計金額",
  total_amount_with_tax:"合計金額(税込)",
  create_new : "新規作成",
  new_project:"新規案件",
  edit:"編集",
  edit_project:"案件の編集",
  estimate:"見積書",
  invoice:"請求書",
  tax_rate:"税率",
  clone:"複製",

  items:"項目一覧",
  item_name:"項目",
  unit_price:"単価",
  hours:"時間",
  quantity:"数量",
  taxed:"課税",
  tax:"消費税",
  sub_total_amount:'小計',
  amount:'合計',
  add_item:"項目を追加",
  delete_item:"削除",
  save:"保存",
  cancel:"キャンセル",
  delete:"削除",
  delete_project:"案件の削除",
  back_to_top:"トップに戻る",
};

module.exports = labels;
